pipeline {
    agent any
    tools{
        maven 'apache-maven-3.9.3'
    }
    stages{
        stage("Checkout the project") {
           steps{
               git branch: 'main', credentialsId: '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', url: 'https://github.com/ashokvb/Simplilearn'
           } 
        }
        stage("Build the Maven package"){
            steps {
                sh 'mvn clean package'
            }
        }
    }
}
